### ISSUE TITLE
Provide RAII wrapper for managing workspace memory

### ISSUE THREAD

**Issue by OrestZborowski-SIG** [rtosholdings/riptide_cpp#64]
The code uses `WORKSPACE_ALLOC()` (and related) to allocate memory, relying on calling `WORKSPACE_FREE()` to deallocate that memory. This is error-prone, especially while handling errors. It would be preferable to provide an RAII wrapper (e.g. std::unique_ptr) to manage that memory automatically.

**Comment by staffantj** [comment]
+1, especially if it can be done in a way that it would allow pmr-style memory allocation strategy choices to be made.

**Comment by jack-pappas** [comment]
The upcoming numpy 1.22 release will include support for custom, pluggable memory allocators. That means the array-pooling being done with ``WORKSPACE_ALLOC()`` and ``WORKSPACE_FREE()`` could be refactored into a numpy-1.22-compatible allocator API; then that allocator can be installed/uninstalled by the ``riptide_cpp.SetRecycleMode`` function. At that point, you can rip out all of the ``WORKSPACE_ALLOC()`` and ``WORKSPACE_FREE()`` calls and just use the regular numpy C APIs for it, because you'd still be effectively using them (just through the installed numpy allocator). Then, your RAII wrapper can just wrap the regular numpy APIs too, which'll help to keep it relatively simple and fast.
